name: Conventional PR

on:
  pull_request_target:
    types: [opened, reopened, edited, synchronize]

permissions: {}

jobs:
  title:
    name: Conventional PR title
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: azohra/conventional-pr@b7965e3b190643c2ea94b9cb4a01c6a9a020ea46
